import { BaseAgent, BaseAgentConfig, AgentCommandConfig } from "./base";
import { ModelConfig } from "./utils";
import {
  AgentType,
  CodexConfig,
  CodexResponse,
  CodexStreamCallbacks,
  Conversation,
  ModelProvider,
} from "../types";

export class CodexAgent extends BaseAgent {
  private providerApiKey: string;
  private provider: ModelProvider;
  private model?: string;

  private escapePrompt(prompt: string): string {
    // Escape backticks and other special characters
    return prompt.replace(/[`"$\\]/g, "\\$&");
  }

  constructor(config: CodexConfig) {
    const baseConfig: BaseAgentConfig = {
      githubToken: config.githubToken,
      repoUrl: config.repoUrl,
      sandboxProvider: config.sandboxProvider,
      secrets: config.secrets,
      sandboxId: config.sandboxId,
      telemetry: config.telemetry,
      workingDirectory: config.workingDirectory,
      mcpConfig: config.mcpConfig,
    };

    super(baseConfig);

    // Support new providerApiKey field with fallback to deprecated fields for backward compatibility
    this.providerApiKey = config.providerApiKey || "";
    this.provider = config.provider || "openai";
    this.model = config.model;

    if (!this.providerApiKey) {
      throw new Error(
        "Provider API key is required. Please provide providerApiKey, apiKey, or openaiApiKey."
      );
    }
  }

  protected getCommandConfig(
    prompt: string,
    mode?: "ask" | "code"
  ): AgentCommandConfig {
    let instruction: string;
    if (mode === "ask") {
      instruction =
        "Research the repository and answer the user's questions. " +
        "Do NOT make any changes to any files in the repository.";
    } else {
      instruction =
        "Do the necessary changes to the codebase based on the users input.\n" +
        "Don't ask any follow up questions.";
    }

    const escapedPrompt = this.escapePrompt(prompt);
    let _prompt = `${instruction}\n\nUser: ${escapedPrompt}`;

    return {
      command: `codex --full-auto${
        this.model ? ` --model ${this.model}` : ""
      }${
        this.provider ? ` --provider ${this.provider}` : ""
      } --quiet "${_prompt}"`,
      errorPrefix: "Codex",
      labelName: "codex",
      labelColor: "ededed",
      labelDescription: "Pull requests generated by Codex agent",
    };
  }

  protected getDefaultTemplate(): string {
    return "vibekit-codex";
  }

  protected getEnvironmentVariables(): Record<string, string> {
    const envKey = `${this.provider.toUpperCase()}_API_KEY`;
    return {
      [envKey]: this.providerApiKey,
    };
  }

  protected getApiKey(): string {
    return this.providerApiKey;
  }

  protected getAgentType(): AgentType {
    return "codex";
  }

  protected getModelConfig(): ModelConfig {
    return {
      provider: this.provider,
      apiKey: this.providerApiKey,
      model: this.model,
    };
  }

  // Override generateCode to support history and MCP tools
  public async generateCode(
    prompt: string,
    mode?: "ask" | "code",
    branch?: string,
    history?: Conversation[],
    callbacks?: CodexStreamCallbacks,
    background?: boolean
  ): Promise<CodexResponse> {
    // Get available MCP tools
    const availableTools = await this.getAvailableTools();
    
    let instruction: string;

    if (mode === "ask") {
      instruction =
        "Research the repository and answer the user's questions. " +
        "Do NOT make any changes to any files in the repository.";
    } else {
      instruction =
        "Do the necessary changes to the codebase based on the users input.\n" +
        "Don't ask any follow up questions.";
    }

    const escapedPrompt = this.escapePrompt(prompt);
    let _prompt = `${instruction}\n\nUser: ${escapedPrompt}`;

    if (history) {
      _prompt += `\n\nConversation history: ${history
        .map((h) => `${h.role}\n ${h.content}`)
        .join("\n\n")}`;
    }
    
    // Add MCP tools information to prompt if available
    if (availableTools.length > 0) {
      const toolDescriptions = availableTools.map(tool => 
        `- ${tool.name}: ${tool.description}`
      ).join('\n');
      _prompt += `\n\nAvailable MCP tools:\n${toolDescriptions}\n` +
        "You can reference these tools by using [TOOL_CALL:toolname]args[/TOOL_CALL] format.";
    }
    
    // Override the command config with MCP-aware prompt
    const originalGetCommandConfig = this.getCommandConfig.bind(this);
    this.getCommandConfig = (p: string, m?: "ask" | "code") => ({
      ...originalGetCommandConfig(p, m),
      command: `codex --full-auto${
        this.model ? ` --model ${this.model}` : ""
      }${
        this.provider ? ` --provider ${this.provider}` : ""
      } --quiet "${_prompt}"`,
    });

    const result = await super.generateCode(
      prompt,
      mode,
      branch,
      history,
      callbacks,
      background
    );

    // Restore original method
    this.getCommandConfig = originalGetCommandConfig;

    // Process result for MCP tool calls if needed
    return await this.processMCPResponse(result as CodexResponse, availableTools);
  }

  /**
   * Process Codex response and execute any MCP tool calls
   */
  private async processMCPResponse(
    response: CodexResponse, 
    availableTools: any[]
  ): Promise<CodexResponse> {
    if (!availableTools.length || !response.stdout) {
      return response;
    }

    try {
      let processedStdout = response.stdout;
      const toolCallRegex = /\[TOOL_CALL:(\w+)\](.+?)\[\/TOOL_CALL\]/gs;
      const toolCalls = [...response.stdout.matchAll(toolCallRegex)];
      
      for (const [fullMatch, toolName, argsStr] of toolCalls) {
        try {
          const args = JSON.parse(argsStr.trim());
          const toolResult = await this.executeMCPTool(toolName, args);
          
          // Replace the tool call with the result
          const resultText = `[TOOL_RESULT:${toolName}]${JSON.stringify(toolResult)}[/TOOL_RESULT]`;
          processedStdout = processedStdout.replace(fullMatch, resultText);
          
        } catch (error) {
          console.warn(`Failed to execute MCP tool ${toolName}:`, (error as Error)?.message || error);
          const errorText = `[TOOL_ERROR:${toolName}]${(error as Error)?.message || error}[/TOOL_ERROR]`;
          processedStdout = processedStdout.replace(fullMatch, errorText);
        }
      }

      return {
        ...response,
        stdout: processedStdout,
        mcpToolsUsed: toolCalls.length
      };
      
    } catch (error) {
      console.warn('Error processing MCP response:', (error as Error)?.message || error);
      return response;
    }
  }
}
