# Proxy Redaction Configuration
secrets:
  # Environment variables to redact (supports wildcards)
  env_vars:
    - "AWS_*"
    - "GCP_*"
    - "AZURE_*"
    - "OPENAI_API_KEY"
    - "ANTHROPIC_API_KEY"
    - "GROK_API_KEY"
    - "*_API_KEY"
    - "*_SECRET*"
    - "*_TOKEN*"
    - "*_PASSWORD*"
    - "DATABASE_URL"
    - "DATABASE_PASSWORD"
    - "JWT_SECRET"
    - "SECRET_KEY"
    - "API_KEY"
    - "GITHUB_TOKEN"

  # Regex patterns for detecting secrets
  patterns:
    - name: "aws_access_key"
      regex: "AKIA[0-9A-Z]{16}"
    
    - name: "aws_secret_key"
      regex: "[A-Za-z0-9/+=]{40}"
    
    - name: "jwt_token"
      regex: "eyJ[A-Za-z0-9-_]+\\.[A-Za-z0-9-_]+\\.[A-Za-z0-9-_]+"
    
    - name: "github_token"
      regex: "ghp_[A-Za-z0-9]{36}"
    
    - name: "grok_api_key"
      regex: "xai-[A-Za-z0-9]+"
    
    - name: "anthropic_api_key"
      regex: "sk-ant-api03-[A-Za-z0-9_-]+"
    
    - name: "generic_api_key_32"
      regex: "[a-zA-Z0-9]{32}"
    
    - name: "generic_api_key_64"
      regex: "[a-zA-Z0-9]{64}"